// =============================================
// SCHALOM ISRAEL - Wortliste fuer die Gematria
//
// Bewusst kuratiert statt maschinell aus dem Text gezogen: "Dein Name hat
// denselben Wert wie X" ist nur interessant, wenn X ein Wort mit Bedeutung
// ist. Zufallstreffer aus dem Fliesstext waeren wertlos.
//
// Die Zahlenwerte stehen NICHT in dieser Datei. Sie werden aus der Schreibweise
// berechnet, damit sich kein Rechenfehler einschleichen kann.
//
// UMD, damit ohne Browser testbar.
// =============================================
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.GematriaWoerter = factory();
})(typeof self !== 'undefined' ? self : this, function () {

  const WOERTER = [
    // Grundbegriffe des Glaubens
    { w: 'אחד', t: 'echad', b: 'eins, einzig' },
    { w: 'אהבה', t: 'ahawa', b: 'Liebe' },
    { w: 'אמת', t: 'emet', b: 'Wahrheit' },
    { w: 'אמונה', t: 'emuna', b: 'Treue, Vertrauen' },
    { w: 'שלום', t: 'schalom', b: 'Frieden, Ganzheit' },
    { w: 'תורה', t: 'tora', b: 'Weisung, Tora' },
    { w: 'ברכה', t: 'beracha', b: 'Segen' },
    { w: 'חסד', t: 'chesed', b: 'treue Zuwendung' },
    { w: 'רחמים', t: 'rachamim', b: 'Erbarmen' },
    { w: 'צדק', t: 'zedek', b: 'Gerechtigkeit' },
    { w: 'צדקה', t: 'zedaka', b: 'Gerechtigkeit, Wohltun' },
    { w: 'משפט', t: 'mischpat', b: 'Recht, Urteil' },
    { w: 'קדוש', t: 'kadosch', b: 'heilig, abgesondert' },
    { w: 'תשובה', t: 'teschuwa', b: 'Umkehr, Rückkehr' },
    { w: 'תפלה', t: 'tefila', b: 'Gebet' },
    { w: 'כבוד', t: 'kawod', b: 'Ehre, Gewicht' },
    { w: 'חכמה', t: 'chochma', b: 'Weisheit' },
    { w: 'בינה', t: 'bina', b: 'Einsicht' },
    { w: 'דעת', t: 'daat', b: 'Erkenntnis' },
    { w: 'יראה', t: 'jira', b: 'Ehrfurcht' },
    { w: 'ענוה', t: 'anawa', b: 'Demut' },
    { w: 'סבלנות', t: 'sawlanut', b: 'Geduld' },
    { w: 'שמחה', t: 'simcha', b: 'Freude' },
    { w: 'תקוה', t: 'tikwa', b: 'Hoffnung' },
    { w: 'נחמה', t: 'nechama', b: 'Trost' },
    { w: 'גאולה', t: 'geula', b: 'Erlösung' },
    { w: 'ברית', t: 'brit', b: 'Bund' },
    { w: 'מצוה', t: 'mizwa', b: 'Gebot' },
    { w: 'הלכה', t: 'halacha', b: 'Weg, Lebensregel' },
    { w: 'זכות', t: 'sechut', b: 'Verdienst' },

    // Mensch und Leben
    { w: 'חי', t: 'chai', b: 'lebendig' },
    { w: 'חיים', t: 'chajim', b: 'Leben' },
    { w: 'נפש', t: 'nefesch', b: 'Kehle, Lebewesen, Seele' },
    { w: 'רוח', t: 'ruach', b: 'Wind, Atem, Geist' },
    { w: 'נשמה', t: 'neschama', b: 'Atem, Seele' },
    { w: 'לב', t: 'lew', b: 'Herz' },
    { w: 'אדם', t: 'adam', b: 'Mensch' },
    { w: 'איש', t: 'isch', b: 'Mann' },
    { w: 'אשה', t: 'ischa', b: 'Frau' },
    { w: 'בן', t: 'ben', b: 'Sohn' },
    { w: 'בת', t: 'bat', b: 'Tochter' },
    { w: 'אב', t: 'aw', b: 'Vater' },
    { w: 'אם', t: 'em', b: 'Mutter' },
    { w: 'אח', t: 'ach', b: 'Bruder' },
    { w: 'רע', t: 'rea', b: 'Nächster, Freund' },
    { w: 'עם', t: 'am', b: 'Volk' },
    { w: 'יד', t: 'jad', b: 'Hand' },
    { w: 'עין', t: 'ajin', b: 'Auge, Quelle' },
    { w: 'פה', t: 'pe', b: 'Mund' },
    { w: 'קול', t: 'kol', b: 'Stimme' },
    { w: 'שם', t: 'schem', b: 'Name' },
    { w: 'דבר', t: 'dawar', b: 'Wort, Sache' },
    { w: 'זכר', t: 'secher / sachar', b: 'Gedenken; gedenken' },

    // Schoepfung und Welt
    { w: 'אור', t: 'or', b: 'Licht' },
    { w: 'חשך', t: 'choschech', b: 'Finsternis' },
    { w: 'שמים', t: 'schamajim', b: 'Himmel' },
    { w: 'ארץ', t: 'erez', b: 'Land, Erde' },
    { w: 'מים', t: 'majim', b: 'Wasser' },
    { w: 'אש', t: 'esch', b: 'Feuer' },
    { w: 'עץ', t: 'ez', b: 'Baum, Holz' },
    { w: 'גן', t: 'gan', b: 'Garten' },
    { w: 'הר', t: 'har', b: 'Berg' },
    { w: 'מדבר', t: 'midbar', b: 'Wüste' },
    { w: 'ים', t: 'jam', b: 'Meer' },
    { w: 'דרך', t: 'derech', b: 'Weg' },
    { w: 'בית', t: 'bajit', b: 'Haus' },
    { w: 'שער', t: 'schaar', b: 'Tor' },
    { w: 'אבן', t: 'ewen', b: 'Stein' },
    { w: 'לחם', t: 'lechem', b: 'Brot' },
    { w: 'יין', t: 'jajin', b: 'Wein' },
    { w: 'שמן', t: 'schemen', b: 'Öl' },
    { w: 'זהב', t: 'sahaw', b: 'Gold' },
    { w: 'כסף', t: 'kesef', b: 'Silber, Geld' },
    { w: 'סלם', t: 'sulam', b: 'Leiter' },
    { w: 'ענן', t: 'anan', b: 'Wolke' },
    { w: 'מטר', t: 'matar', b: 'Regen' },
    { w: 'כוכב', t: 'kochaw', b: 'Stern' },
    { w: 'שמש', t: 'schemesch', b: 'Sonne' },
    { w: 'ירח', t: 'jareach', b: 'Mond' },

    // Zeit und Fest
    { w: 'יום', t: 'jom', b: 'Tag' },
    { w: 'לילה', t: 'lajla', b: 'Nacht' },
    { w: 'שנה', t: 'schana', b: 'Jahr' },
    { w: 'שבת', t: 'schabbat', b: 'Schabbat, Ruhe' },
    { w: 'חדש', t: 'chodesch', b: 'Monat, Neumond' },
    { w: 'מועד', t: 'moed', b: 'Festzeit' },
    { w: 'פסח', t: 'pessach', b: 'Pessach' },
    { w: 'סוכה', t: 'sukka', b: 'Laubhütte' },
    { w: 'יובל', t: 'jowel', b: 'Jubeljahr' },
    { w: 'עולם', t: 'olam', b: 'Welt, Ewigkeit' },
    { w: 'נצח', t: 'nezach', b: 'Dauer, Sieg' },

    // Tora, Kult, Heiligtum
    { w: 'משכן', t: 'mischkan', b: 'Wohnung, Stiftszelt' },
    { w: 'מקדש', t: 'mikdasch', b: 'Heiligtum' },
    { w: 'מזבח', t: 'misbeach', b: 'Altar' },
    { w: 'ארון', t: 'aron', b: 'Lade' },
    { w: 'מנורה', t: 'menora', b: 'Leuchter' },
    { w: 'כהן', t: 'kohen', b: 'Priester' },
    { w: 'לוי', t: 'lewi', b: 'Levi' },
    { w: 'נביא', t: 'nawi', b: 'Prophet' },
    { w: 'מלך', t: 'melech', b: 'König' },
    { w: 'שופר', t: 'schofar', b: 'Widderhorn' },
    { w: 'ציצית', t: 'zizit', b: 'Schaufäden' },
    { w: 'מזוזה', t: 'mesusa', b: 'Türpfosten, Mesusa' },
    { w: 'קרבן', t: 'korban', b: 'Opfergabe, Annäherung' },

    // Namen aus dem Tanach
    { w: 'ישראל', t: 'Jisrael', b: 'Israel' },
    { w: 'ירושלים', t: 'Jeruschalajim', b: 'Jerusalem' },
    { w: 'ציון', t: 'Zion', b: 'Zion' },
    { w: 'סיני', t: 'Sinai', b: 'Sinai' },
    { w: 'אברהם', t: 'Awraham', b: 'Abraham' },
    { w: 'יצחק', t: 'Jizchak', b: 'Isaak' },
    { w: 'יעקב', t: 'Jaakow', b: 'Jakob' },
    { w: 'שרה', t: 'Sara', b: 'Sara' },
    { w: 'רבקה', t: 'Riwka', b: 'Rebekka' },
    { w: 'רחל', t: 'Rachel', b: 'Rahel' },
    { w: 'לאה', t: 'Lea', b: 'Lea' },
    { w: 'משה', t: 'Mosche', b: 'Mose' },
    { w: 'אהרן', t: 'Aharon', b: 'Aaron' },
    { w: 'מרים', t: 'Mirjam', b: 'Mirjam' },
    { w: 'דוד', t: 'David', b: 'David' },
    { w: 'שלמה', t: 'Schlomo', b: 'Salomo' },
    { w: 'שמואל', t: 'Schmuel', b: 'Samuel' },
    { w: 'יהושע', t: 'Jehoschua', b: 'Josua' },
    { w: 'אליהו', t: 'Elijahu', b: 'Elia' },
    { w: 'ישעיהו', t: 'Jeschajahu', b: 'Jesaja' },
    { w: 'רות', t: 'Rut', b: 'Rut' },
    { w: 'אסתר', t: 'Ester', b: 'Ester' },
    { w: 'חנה', t: 'Chana', b: 'Hanna' },
    { w: 'יהודה', t: 'Jehuda', b: 'Juda' },
    { w: 'יוסף', t: 'Josef', b: 'Josef' },
    { w: 'בנימין', t: 'Binjamin', b: 'Benjamin' },
    { w: 'נח', t: 'Noach', b: 'Noah' },
    { w: 'חוה', t: 'Chawa', b: 'Eva' },

    // Weitere Begriffe mit Gewicht
    { w: 'טוב', t: 'tow', b: 'gut' },
    { w: 'גדול', t: 'gadol', b: 'groß' },
    { w: 'קטן', t: 'katan', b: 'klein' },
    { w: 'חזק', t: 'chasak', b: 'stark' },
    { w: 'רך', t: 'rach', b: 'weich, zart' },
    { w: 'כח', t: 'koach', b: 'Kraft' },
    { w: 'עז', t: 'os / es', b: 'Stärke; Ziege' },
    { w: 'מלאך', t: 'malach', b: 'Bote, Engel' },
    { w: 'נס', t: 'nes', b: 'Zeichen, Wunder' },
    { w: 'אות', t: 'ot', b: 'Zeichen, Buchstabe' },
    { w: 'ספר', t: 'sefer / sipper', b: 'Buch, Schriftrolle; erzählen' },
    { w: 'כתב', t: 'ktaw / katav', b: 'Schrift; schreiben' },
    { w: 'קרא', t: 'kara', b: 'rufen, lesen' },
    { w: 'שמע', t: 'schema', b: 'höre' },
    { w: 'הלל', t: 'hallel', b: 'Lobpreis' },
    { w: 'שיר', t: 'schir', b: 'Lied' },
    { w: 'זמר', t: 'semer', b: 'Gesang' },
    { w: 'חלום', t: 'chalom', b: 'Traum' },
    { w: 'מלאכה', t: 'melacha', b: 'Werk, Arbeit' },
    { w: 'מנוחה', t: 'menucha', b: 'Ruhe' },
    { w: 'חרות', t: 'cherut', b: 'Freiheit' },
    { w: 'גלות', t: 'galut', b: 'Verbannung' },
    { w: 'קהל', t: 'kahal', b: 'Versammlung' },
    { w: 'עדה', t: 'eda', b: 'Gemeinde' },
    { w: 'שבט', t: 'schewet', b: 'Stamm, Stab' },
    { w: 'מטה', t: 'mate / mata', b: 'Stab, Stamm; unten' },
    { w: 'דם', t: 'dam', b: 'Blut' },
    { w: 'בשר', t: 'bassar', b: 'Fleisch' },
    { w: 'עצם', t: 'ezem', b: 'Knochen, Wesen' },
    { w: 'זרע', t: 'sera / sara', b: 'Same, Nachkommen; säen' },
    { w: 'פרי', t: 'pri', b: 'Frucht' },
    { w: 'שדה', t: 'sade', b: 'Feld' },
    { w: 'צאן', t: 'zon', b: 'Kleinvieh' },
    { w: 'רעה', t: 'roe', b: 'Hirte' },
    { w: 'כבש', t: 'kewes', b: 'Lamm' },
    { w: 'איל', t: 'ajil', b: 'Widder' },
    { w: 'יונה', t: 'jona', b: 'Taube' },
    { w: 'נשר', t: 'nescher', b: 'Adler' },
    { w: 'ארי', t: 'ari', b: 'Löwe' },
    { w: 'נחש', t: 'nachasch', b: 'Schlange' },
    { w: 'שקר', t: 'scheker', b: 'Lüge' },
    { w: 'חטא', t: 'chet', b: 'Verfehlung' },
    { w: 'מות', t: 'mawet', b: 'Tod' },
    { w: 'קבר', t: 'kewer', b: 'Grab' },
    { w: 'יתום', t: 'jatom', b: 'Waise' },
    { w: 'אלמנה', t: 'almana', b: 'Witwe' },
    { w: 'גר', t: 'ger', b: 'Fremder, Zugewanderter' },
    { w: 'עני', t: 'ani', b: 'Armer' },
    { w: 'מלחמה', t: 'milchama', b: 'Krieg' },
    { w: 'חרב', t: 'cherew', b: 'Schwert' },
    { w: 'מגן', t: 'magen', b: 'Schild' },
    { w: 'עבד', t: 'ewed', b: 'Knecht, Diener' },
    { w: 'חפש', t: 'chofesch', b: 'Freiheit' },

    // ---------- Eigenschaften des Menschen ----------
    { w: 'צדיק', t: 'zadik', b: 'gerecht, Gerechter' },
    { w: 'חסיד', t: 'chassid', b: 'fromm, hingebungsvoll' },
    { w: 'תמים', t: 'tamim', b: 'lauter, ganz' },
    { w: 'ישר', t: 'jaschar', b: 'aufrecht, gerade' },
    { w: 'נאמן', t: 'neeman', b: 'verlässlich, treu' },
    { w: 'חכם', t: 'chacham', b: 'weise' },
    { w: 'נבון', t: 'nawon', b: 'einsichtig' },
    { w: 'ענו', t: 'anaw', b: 'demütig' },
    { w: 'גאה', t: 'gee', b: 'stolz, hochmütig' },
    { w: 'רשע', t: 'rascha', b: 'schuldig, frevelhaft' },
    { w: 'כסיל', t: 'ksil', b: 'töricht' },
    { w: 'אויל', t: 'ewil', b: 'närrisch' },
    { w: 'עצל', t: 'azel', b: 'träge' },
    { w: 'חרוץ', t: 'charuz', b: 'fleißig' },
    { w: 'זריז', t: 'saris', b: 'flink, tatkräftig' },
    { w: 'אמיץ', t: 'amiz', b: 'mutig' },
    { w: 'ירא', t: 'jare', b: 'ehrfürchtig' },
    { w: 'רחום', t: 'rachum', b: 'barmherzig' },
    { w: 'חנון', t: 'chanun', b: 'gnädig' },
    { w: 'סבלן', t: 'sawlan', b: 'geduldig' },
    { w: 'נדיב', t: 'nadiw', b: 'freigebig' },
    { w: 'קנא', t: 'kana', b: 'eifernd' },
    { w: 'שמח', t: 'sameach', b: 'fröhlich' },
    { w: 'עצוב', t: 'azuw', b: 'traurig' },
    { w: 'שקט', t: 'schaket', b: 'ruhig, still' },
    { w: 'טהור', t: 'tahor', b: 'rein' },
    { w: 'טמא', t: 'tame', b: 'unrein' },
    { w: 'נקי', t: 'naki', b: 'schuldlos, sauber' },
    { w: 'זקן', t: 'saken', b: 'alt, Ältester' },
    { w: 'נער', t: 'naar', b: 'Junge, junger Mann' },
    { w: 'בחור', t: 'bachur', b: 'Erwählter, junger Mann' },
    { w: 'גבור', t: 'gibor', b: 'Held, stark' },
    { w: 'חלש', t: 'chalasch', b: 'schwach' },
    { w: 'עשיר', t: 'aschir', b: 'reich' },
    { w: 'דל', t: 'dal', b: 'gering, arm' },
    { w: 'שלם', t: 'schalem', b: 'ganz, unversehrt' },
    { w: 'רחוק', t: 'rachok', b: 'fern' },
    { w: 'קרוב', t: 'karow', b: 'nah' },

    // ---------- Innere Zustände ----------
    { w: 'כעס', t: 'kaas', b: 'Zorn' },
    { w: 'אף', t: 'af', b: 'Nase, Zorn' },
    { w: 'חמה', t: 'chema', b: 'Grimm' },
    { w: 'פחד', t: 'pachad', b: 'Furcht' },
    { w: 'חרדה', t: 'charada', b: 'Beben, Angst' },
    { w: 'בטחון', t: 'bitachon', b: 'Zuversicht' },
    { w: 'דאגה', t: 'deaga', b: 'Sorge' },
    { w: 'צער', t: 'zaar', b: 'Kummer' },
    { w: 'אבל', t: 'ewel', b: 'Trauer' },
    { w: 'גיל', t: 'gil', b: 'Jubel' },
    { w: 'ששון', t: 'sasson', b: 'Wonne' },
    { w: 'רצון', t: 'razon', b: 'Wille, Wohlgefallen' },
    { w: 'תאוה', t: 'taawa', b: 'Begehren' },
    { w: 'קנאה', t: 'kina', b: 'Eifersucht' },
    { w: 'שנאה', t: 'sina', b: 'Hass' },
    { w: 'בושה', t: 'buscha', b: 'Scham' },
    { w: 'חרטה', t: 'charata', b: 'Reue' },
    { w: 'מחילה', t: 'mechila', b: 'Vergebung' },
    { w: 'סליחה', t: 'slicha', b: 'Verzeihung' },
    { w: 'כפרה', t: 'kappara', b: 'Sühne' },
    { w: 'זכרון', t: 'sikaron', b: 'Erinnerung' },
    { w: 'מחשבה', t: 'machschawa', b: 'Gedanke' },
    { w: 'כונה', t: 'kawana', b: 'Absicht, Ausrichtung' },
    { w: 'לבב', t: 'lewaw', b: 'Herz, Inneres' },
    { w: 'כליות', t: 'klajot', b: 'Nieren, Innerstes' },

    // ---------- Tun und Lassen ----------
    { w: 'ברא', t: 'bara', b: 'erschaffen' },
    { w: 'עשה', t: 'assa', b: 'machen, tun' },
    { w: 'אמר', t: 'amar', b: 'sagen' },
    { w: 'הלך', t: 'halach', b: 'gehen' },
    { w: 'בוא', t: 'bo', b: 'kommen' },
    { w: 'ישב', t: 'jaschaw', b: 'sitzen, wohnen' },
    { w: 'קום', t: 'kum', b: 'aufstehen' },
    { w: 'נתן', t: 'natan', b: 'geben' },
    { w: 'לקח', t: 'lakach', b: 'nehmen' },
    { w: 'ראה', t: 'raa', b: 'sehen' },
    { w: 'ידע', t: 'jada', b: 'erkennen' },
    { w: 'אהב', t: 'ahaw', b: 'lieben' },
    { w: 'שכח', t: 'schachach', b: 'vergessen' },
    { w: 'שמר', t: 'schamar', b: 'bewahren' },
    { w: 'למד', t: 'lamad', b: 'lernen, lehren' },
    { w: 'שאל', t: 'schaal', b: 'fragen' },
    { w: 'ענה', t: 'ana', b: 'antworten' },
    { w: 'בחר', t: 'bachar', b: 'erwählen' },
    { w: 'שלח', t: 'schalach', b: 'senden' },
    { w: 'בנה', t: 'bana', b: 'bauen' },
    { w: 'קצר', t: 'kazar', b: 'ernten' },
    { w: 'אכל', t: 'achal', b: 'essen' },
    { w: 'שתה', t: 'schata', b: 'trinken' },
    { w: 'ישן', t: 'jaschen', b: 'schlafen' },
    { w: 'קרב', t: 'karaw', b: 'sich nähern' },
    { w: 'ברח', t: 'barach', b: 'fliehen' },
    { w: 'שוב', t: 'schuw', b: 'umkehren, zurückkehren' },
    { w: 'עמד', t: 'amad', b: 'stehen, bestehen' },
    { w: 'נשא', t: 'nassa', b: 'tragen, erheben' },
    { w: 'ברך', t: 'berach', b: 'segnen' },
    { w: 'הודה', t: 'hoda', b: 'danken, bekennen' },
    { w: 'צוה', t: 'ziwa', b: 'gebieten' },
    { w: 'שפט', t: 'schafat', b: 'richten' },
    { w: 'גאל', t: 'gaal', b: 'auslösen, erlösen' },
    { w: 'רפא', t: 'rafa', b: 'heilen' },
    { w: 'הרג', t: 'harag', b: 'töten' },
    { w: 'גנב', t: 'ganaw', b: 'stehlen' },

    // ---------- Sprache und Denken ----------
    { w: 'לשון', t: 'laschon', b: 'Zunge, Sprache' },
    { w: 'שפה', t: 'safa', b: 'Lippe, Sprache' },
    { w: 'משל', t: 'maschal', b: 'Gleichnis, Spruch' },
    { w: 'חידה', t: 'chida', b: 'Rätsel' },
    { w: 'סוד', t: 'sod', b: 'Geheimnis, vertrauter Kreis' },
    { w: 'פשט', t: 'pschat', b: 'einfacher Wortsinn' },
    { w: 'רמז', t: 'remes', b: 'Andeutung' },
    { w: 'דרש', t: 'drasch', b: 'Auslegung' },
    { w: 'טעם', t: 'taam', b: 'Geschmack, Sinn' },
    { w: 'ערך', t: 'erech', b: 'Wert, Ordnung' },
    { w: 'מדה', t: 'mida', b: 'Maß, Eigenschaft' },
    { w: 'חשבון', t: 'cheschbon', b: 'Rechnung, Bilanz' },
    { w: 'מספר', t: 'mispar', b: 'Zahl' },

    // ---------- Zeit ----------
    { w: 'עת', t: 'et', b: 'Zeit' },
    { w: 'רגע', t: 'rega', b: 'Augenblick' },
    { w: 'שעה', t: 'schaa', b: 'Stunde' },
    { w: 'בקר', t: 'boker', b: 'Morgen' },
    { w: 'ערב', t: 'erew', b: 'Abend' },
    { w: 'צהרים', t: 'zohorajim', b: 'Mittag' },
    { w: 'אתמול', t: 'etmol', b: 'gestern' },
    { w: 'מחר', t: 'machar', b: 'morgen' },
    { w: 'תמיד', t: 'tamid', b: 'beständig, immer' },
    { w: 'ראשון', t: 'rischon', b: 'erster' },
    { w: 'אחרון', t: 'acharon', b: 'letzter' },
    { w: 'קדם', t: 'kedem', b: 'Vorzeit, Osten' },
    { w: 'עתיד', t: 'atid', b: 'Zukunft' },
    { w: 'דור', t: 'dor', b: 'Generation' },

    // ---------- Raum und Richtung ----------
    { w: 'מזרח', t: 'misrach', b: 'Osten' },
    { w: 'מערב', t: 'maaraw', b: 'Westen' },
    { w: 'צפון', t: 'zafon', b: 'Norden' },
    { w: 'דרום', t: 'darom', b: 'Süden' },
    { w: 'מעלה', t: 'maala', b: 'oben, Stufe' },
    { w: 'פנים', t: 'panim', b: 'Gesicht, Vorderseite' },
    { w: 'אחור', t: 'achor', b: 'Rückseite' },
    { w: 'תוך', t: 'toch', b: 'Mitte, Inneres' },
    { w: 'גבול', t: 'gwul', b: 'Grenze' },
    { w: 'מקום', t: 'makom', b: 'Ort' },
    { w: 'עיר', t: 'ir', b: 'Stadt' },
    { w: 'כפר', t: 'kfar', b: 'Dorf' },
    { w: 'אהל', t: 'ohel', b: 'Zelt' },
    { w: 'חצר', t: 'chazer', b: 'Hof' },
    { w: 'חומה', t: 'choma', b: 'Mauer' },
    { w: 'דלת', t: 'delet', b: 'Tür' },
    { w: 'חלון', t: 'chalon', b: 'Fenster' },
    { w: 'נהר', t: 'nahar', b: 'Fluss' },
    { w: 'באר', t: 'beer', b: 'Brunnen' },
    { w: 'מעין', t: 'maajan', b: 'Quelle' },
    { w: 'עמק', t: 'emek', b: 'Tal' },
    { w: 'שדי', t: 'sadai', b: 'Feld, Flur' },
    { w: 'יער', t: 'jaar', b: 'Wald' },
    { w: 'אדמה', t: 'adama', b: 'Erdboden' },
    { w: 'עפר', t: 'afar', b: 'Staub' },
    { w: 'חול', t: 'chol', b: 'Sand' },
    { w: 'סלע', t: 'sela', b: 'Fels' },
    { w: 'צור', t: 'zur', b: 'Fels, Halt' },

    // ---------- Was wächst und lebt ----------
    { w: 'גפן', t: 'gefen', b: 'Weinstock' },
    { w: 'תאנה', t: 'teena', b: 'Feigenbaum' },
    { w: 'זית', t: 'sajit', b: 'Olive' },
    { w: 'רמון', t: 'rimon', b: 'Granatapfel' },
    { w: 'תמר', t: 'tamar', b: 'Dattelpalme' },
    { w: 'ארז', t: 'eres', b: 'Zeder' },
    { w: 'שושנה', t: 'schoschana', b: 'Lilie, Rose' },
    { w: 'עשב', t: 'essew', b: 'Gras, Kraut' },
    { w: 'שורש', t: 'schoresch', b: 'Wurzel' },
    { w: 'ענף', t: 'anaf', b: 'Zweig' },
    { w: 'עלה', t: 'ale', b: 'Blatt' },
    { w: 'חטה', t: 'chita', b: 'Weizen' },
    { w: 'שעורה', t: 'seora', b: 'Gerste' },
    { w: 'דבש', t: 'dwasch', b: 'Honig' },
    { w: 'חלב', t: 'chalaw', b: 'Milch' },
    { w: 'מלח', t: 'melach', b: 'Salz' },
    { w: 'סוס', t: 'sus', b: 'Pferd' },
    { w: 'חמור', t: 'chamor', b: 'Esel' },
    { w: 'גמל', t: 'gamal', b: 'Kamel' },
    { w: 'שור', t: 'schor', b: 'Rind' },
    { w: 'פרה', t: 'para', b: 'Kuh' },
    { w: 'דג', t: 'dag', b: 'Fisch' },
    { w: 'צפור', t: 'zipor', b: 'Vogel' },
    { w: 'דבורה', t: 'dwora', b: 'Biene' },
    { w: 'זאב', t: 'seew', b: 'Wolf' },
    { w: 'דב', t: 'dow', b: 'Bär' },

    // ---------- Volk, Recht, Ordnung ----------
    { w: 'גוי', t: 'goj', b: 'Volk, Nation' },
    { w: 'משפחה', t: 'mischpacha', b: 'Familie' },
    { w: 'נחלה', t: 'nachala', b: 'Erbteil' },
    { w: 'ירושה', t: 'jeruscha', b: 'Erbe' },
    { w: 'עדות', t: 'edut', b: 'Zeugnis' },
    { w: 'עד', t: 'ed', b: 'Zeuge' },
    { w: 'שבועה', t: 'schwua', b: 'Schwur' },
    { w: 'נדר', t: 'neder', b: 'Gelübde' },
    { w: 'חק', t: 'chok', b: 'Satzung' },
    { w: 'תורת', t: 'torat', b: 'Weisung über' },
    { w: 'דין', t: 'din', b: 'Recht, Gericht' },
    { w: 'ענש', t: 'onesch', b: 'Strafe' },
    { w: 'שכר', t: 'sachar', b: 'Lohn' },
    { w: 'מתנה', t: 'matana', b: 'Geschenk' },
    { w: 'מעשר', t: 'maasser', b: 'Zehnter' },
    { w: 'תרומה', t: 'truma', b: 'Abgabe' },
    { w: 'שמיטה', t: 'schmita', b: 'Brachjahr' },
    { w: 'מלכות', t: 'malchut', b: 'Königtum' },
    { w: 'כסא', t: 'kisse', b: 'Thron' },
    { w: 'כתר', t: 'keter', b: 'Krone' },
    { w: 'שר', t: 'sar', b: 'Fürst, Oberer' },
    { w: 'שופט', t: 'schofet', b: 'Richter' },
    { w: 'סופר', t: 'sofer', b: 'Schreiber' },
    { w: 'רועה', t: 'roe', b: 'Hirte' },
    { w: 'צבא', t: 'zawa', b: 'Heer' },
    { w: 'שלל', t: 'schalal', b: 'Beute' },
    { w: 'שבי', t: 'schwi', b: 'Gefangenschaft' },

    // ---------- Weitere zentrale Begriffe ----------
    { w: 'אמן', t: 'amen', b: 'gewiss, so sei es' },
    { w: 'הן', t: 'hen', b: 'siehe, ja' },
    { w: 'נא', t: 'na', b: 'doch, bitte' },
    { w: 'כן', t: 'ken', b: 'so, ja' },
    { w: 'לא', t: 'lo', b: 'nicht' },
    { w: 'הכל', t: 'hakol', b: 'alles' },
    { w: 'רב', t: 'raw', b: 'viel, groß' },
    { w: 'מעט', t: 'meat', b: 'wenig' },
    { w: 'יחד', t: 'jachad', b: 'zusammen' },
    { w: 'לבד', t: 'lewad', b: 'allein' },
    { w: 'בין', t: 'ben', b: 'zwischen' },
    { w: 'נגד', t: 'neged', b: 'gegenüber' },
    { w: 'תחת', t: 'tachat', b: 'unter, anstelle' },
    { w: 'אחרי', t: 'acharei', b: 'nach' },
    { w: 'לפני', t: 'lifnei', b: 'vor' },
    { w: 'סביב', t: 'sawiw', b: 'ringsum' },
    { w: 'עוד', t: 'od', b: 'noch, wieder' },
    { w: 'אולי', t: 'ulai', b: 'vielleicht' },
    { w: 'למה', t: 'lama', b: 'warum' },
    { w: 'איך', t: 'ech', b: 'wie' },
    { w: 'מי', t: 'mi', b: 'wer' },
    { w: 'מה', t: 'ma', b: 'was' },
  ];

  return WOERTER;
});
