// =============================================
// SCHALOM ISRAEL - Wortliste fuer die Gematria
//
// Bewusst kuratiert statt maschinell aus dem Text gezogen: "Dein Name hat
// denselben Wert wie X" ist nur interessant, wenn X ein Wort mit Bedeutung
// ist. Zufallstreffer aus dem Fliesstext waeren wertlos.
//
// Die Zahlenwerte stehen NICHT in dieser Datei. Sie werden aus der Schreibweise
// berechnet, damit sich kein Rechenfehler einschleichen kann.
//
// UMD, damit ohne Browser testbar.
// =============================================
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.GematriaWoerter = factory();
})(typeof self !== 'undefined' ? self : this, function () {

  const WOERTER = [
    // Grundbegriffe des Glaubens
    { w: 'אחד', t: 'echad', b: 'eins, einzig' },
    { w: 'אהבה', t: 'ahawa', b: 'Liebe' },
    { w: 'אמת', t: 'emet', b: 'Wahrheit' },
    { w: 'אמונה', t: 'emuna', b: 'Treue, Vertrauen' },
    { w: 'שלום', t: 'schalom', b: 'Frieden, Ganzheit' },
    { w: 'תורה', t: 'tora', b: 'Weisung, Tora' },
    { w: 'ברכה', t: 'beracha', b: 'Segen' },
    { w: 'חסד', t: 'chesed', b: 'treue Zuwendung' },
    { w: 'רחמים', t: 'rachamim', b: 'Erbarmen' },
    { w: 'צדק', t: 'zedek', b: 'Gerechtigkeit' },
    { w: 'צדקה', t: 'zedaka', b: 'Gerechtigkeit, Wohltun' },
    { w: 'משפט', t: 'mischpat', b: 'Recht, Urteil' },
    { w: 'קדוש', t: 'kadosch', b: 'heilig, abgesondert' },
    { w: 'תשובה', t: 'teschuwa', b: 'Umkehr, Rückkehr' },
    { w: 'תפלה', t: 'tefila', b: 'Gebet' },
    { w: 'כבוד', t: 'kawod', b: 'Ehre, Gewicht' },
    { w: 'חכמה', t: 'chochma', b: 'Weisheit' },
    { w: 'בינה', t: 'bina', b: 'Einsicht' },
    { w: 'דעת', t: 'daat', b: 'Erkenntnis' },
    { w: 'יראה', t: 'jira', b: 'Ehrfurcht' },
    { w: 'ענוה', t: 'anawa', b: 'Demut' },
    { w: 'סבלנות', t: 'sawlanut', b: 'Geduld' },
    { w: 'שמחה', t: 'simcha', b: 'Freude' },
    { w: 'תקוה', t: 'tikwa', b: 'Hoffnung' },
    { w: 'נחמה', t: 'nechama', b: 'Trost' },
    { w: 'גאולה', t: 'geula', b: 'Erlösung' },
    { w: 'ברית', t: 'brit', b: 'Bund' },
    { w: 'מצוה', t: 'mizwa', b: 'Gebot' },
    { w: 'הלכה', t: 'halacha', b: 'Weg, Lebensregel' },
    { w: 'זכות', t: 'sechut', b: 'Verdienst' },

    // Mensch und Leben
    { w: 'חי', t: 'chai', b: 'lebendig' },
    { w: 'חיים', t: 'chajim', b: 'Leben' },
    { w: 'נפש', t: 'nefesch', b: 'Kehle, Lebewesen, Seele' },
    { w: 'רוח', t: 'ruach', b: 'Wind, Atem, Geist' },
    { w: 'נשמה', t: 'neschama', b: 'Atem, Seele' },
    { w: 'לב', t: 'lew', b: 'Herz' },
    { w: 'אדם', t: 'adam', b: 'Mensch' },
    { w: 'איש', t: 'isch', b: 'Mann' },
    { w: 'אשה', t: 'ischa', b: 'Frau' },
    { w: 'בן', t: 'ben', b: 'Sohn' },
    { w: 'בת', t: 'bat', b: 'Tochter' },
    { w: 'אב', t: 'aw', b: 'Vater' },
    { w: 'אם', t: 'em', b: 'Mutter' },
    { w: 'אח', t: 'ach', b: 'Bruder' },
    { w: 'רע', t: 'rea', b: 'Nächster, Freund' },
    { w: 'עם', t: 'am', b: 'Volk' },
    { w: 'יד', t: 'jad', b: 'Hand' },
    { w: 'עין', t: 'ajin', b: 'Auge, Quelle' },
    { w: 'פה', t: 'pe', b: 'Mund' },
    { w: 'קול', t: 'kol', b: 'Stimme' },
    { w: 'שם', t: 'schem', b: 'Name' },
    { w: 'דבר', t: 'dawar', b: 'Wort, Sache' },
    { w: 'זכר', t: 'secher', b: 'Gedenken' },

    // Schoepfung und Welt
    { w: 'אור', t: 'or', b: 'Licht' },
    { w: 'חשך', t: 'choschech', b: 'Finsternis' },
    { w: 'שמים', t: 'schamajim', b: 'Himmel' },
    { w: 'ארץ', t: 'erez', b: 'Land, Erde' },
    { w: 'מים', t: 'majim', b: 'Wasser' },
    { w: 'אש', t: 'esch', b: 'Feuer' },
    { w: 'עץ', t: 'ez', b: 'Baum, Holz' },
    { w: 'גן', t: 'gan', b: 'Garten' },
    { w: 'הר', t: 'har', b: 'Berg' },
    { w: 'מדבר', t: 'midbar', b: 'Wüste' },
    { w: 'ים', t: 'jam', b: 'Meer' },
    { w: 'דרך', t: 'derech', b: 'Weg' },
    { w: 'בית', t: 'bajit', b: 'Haus' },
    { w: 'שער', t: 'schaar', b: 'Tor' },
    { w: 'אבן', t: 'ewen', b: 'Stein' },
    { w: 'לחם', t: 'lechem', b: 'Brot' },
    { w: 'יין', t: 'jajin', b: 'Wein' },
    { w: 'שמן', t: 'schemen', b: 'Öl' },
    { w: 'זהב', t: 'sahaw', b: 'Gold' },
    { w: 'כסף', t: 'kesef', b: 'Silber, Geld' },
    { w: 'סלם', t: 'sulam', b: 'Leiter' },
    { w: 'ענן', t: 'anan', b: 'Wolke' },
    { w: 'מטר', t: 'matar', b: 'Regen' },
    { w: 'כוכב', t: 'kochaw', b: 'Stern' },
    { w: 'שמש', t: 'schemesch', b: 'Sonne' },
    { w: 'ירח', t: 'jareach', b: 'Mond' },

    // Zeit und Fest
    { w: 'יום', t: 'jom', b: 'Tag' },
    { w: 'לילה', t: 'lajla', b: 'Nacht' },
    { w: 'שנה', t: 'schana', b: 'Jahr' },
    { w: 'שבת', t: 'schabbat', b: 'Schabbat, Ruhe' },
    { w: 'חדש', t: 'chodesch', b: 'Monat, Neumond' },
    { w: 'מועד', t: 'moed', b: 'Festzeit' },
    { w: 'פסח', t: 'pessach', b: 'Pessach' },
    { w: 'סוכה', t: 'sukka', b: 'Laubhütte' },
    { w: 'יובל', t: 'jowel', b: 'Jubeljahr' },
    { w: 'עולם', t: 'olam', b: 'Welt, Ewigkeit' },
    { w: 'נצח', t: 'nezach', b: 'Dauer, Sieg' },

    // Tora, Kult, Heiligtum
    { w: 'משכן', t: 'mischkan', b: 'Wohnung, Stiftszelt' },
    { w: 'מקדש', t: 'mikdasch', b: 'Heiligtum' },
    { w: 'מזבח', t: 'misbeach', b: 'Altar' },
    { w: 'ארון', t: 'aron', b: 'Lade' },
    { w: 'מנורה', t: 'menora', b: 'Leuchter' },
    { w: 'כהן', t: 'kohen', b: 'Priester' },
    { w: 'לוי', t: 'lewi', b: 'Levi' },
    { w: 'נביא', t: 'nawi', b: 'Prophet' },
    { w: 'מלך', t: 'melech', b: 'König' },
    { w: 'שופר', t: 'schofar', b: 'Widderhorn' },
    { w: 'ציצית', t: 'zizit', b: 'Schaufäden' },
    { w: 'מזוזה', t: 'mesusa', b: 'Türpfosten, Mesusa' },
    { w: 'קרבן', t: 'korban', b: 'Opfergabe, Annäherung' },

    // Namen aus dem Tanach
    { w: 'ישראל', t: 'Jisrael', b: 'Israel' },
    { w: 'ירושלים', t: 'Jeruschalajim', b: 'Jerusalem' },
    { w: 'ציון', t: 'Zion', b: 'Zion' },
    { w: 'סיני', t: 'Sinai', b: 'Sinai' },
    { w: 'אברהם', t: 'Awraham', b: 'Abraham' },
    { w: 'יצחק', t: 'Jizchak', b: 'Isaak' },
    { w: 'יעקב', t: 'Jaakow', b: 'Jakob' },
    { w: 'שרה', t: 'Sara', b: 'Sara' },
    { w: 'רבקה', t: 'Riwka', b: 'Rebekka' },
    { w: 'רחל', t: 'Rachel', b: 'Rahel' },
    { w: 'לאה', t: 'Lea', b: 'Lea' },
    { w: 'משה', t: 'Mosche', b: 'Mose' },
    { w: 'אהרן', t: 'Aharon', b: 'Aaron' },
    { w: 'מרים', t: 'Mirjam', b: 'Mirjam' },
    { w: 'דוד', t: 'David', b: 'David' },
    { w: 'שלמה', t: 'Schlomo', b: 'Salomo' },
    { w: 'שמואל', t: 'Schmuel', b: 'Samuel' },
    { w: 'יהושע', t: 'Jehoschua', b: 'Josua' },
    { w: 'אליהו', t: 'Elijahu', b: 'Elia' },
    { w: 'ישעיהו', t: 'Jeschajahu', b: 'Jesaja' },
    { w: 'רות', t: 'Rut', b: 'Rut' },
    { w: 'אסתר', t: 'Ester', b: 'Ester' },
    { w: 'חנה', t: 'Chana', b: 'Hanna' },
    { w: 'יהודה', t: 'Jehuda', b: 'Juda' },
    { w: 'יוסף', t: 'Josef', b: 'Josef' },
    { w: 'בנימין', t: 'Binjamin', b: 'Benjamin' },
    { w: 'נח', t: 'Noach', b: 'Noah' },
    { w: 'חוה', t: 'Chawa', b: 'Eva' },

    // Weitere Begriffe mit Gewicht
    { w: 'טוב', t: 'tow', b: 'gut' },
    { w: 'גדול', t: 'gadol', b: 'groß' },
    { w: 'קטן', t: 'katan', b: 'klein' },
    { w: 'חזק', t: 'chasak', b: 'stark' },
    { w: 'רך', t: 'rach', b: 'weich, zart' },
    { w: 'כח', t: 'koach', b: 'Kraft' },
    { w: 'עז', t: 'os', b: 'Stärke' },
    { w: 'מלאך', t: 'malach', b: 'Bote, Engel' },
    { w: 'נס', t: 'nes', b: 'Zeichen, Wunder' },
    { w: 'אות', t: 'ot', b: 'Zeichen, Buchstabe' },
    { w: 'ספר', t: 'sefer', b: 'Buch, Schriftrolle' },
    { w: 'כתב', t: 'ktaw', b: 'Schrift' },
    { w: 'קרא', t: 'kara', b: 'rufen, lesen' },
    { w: 'שמע', t: 'schema', b: 'höre' },
    { w: 'הלל', t: 'hallel', b: 'Lobpreis' },
    { w: 'שיר', t: 'schir', b: 'Lied' },
    { w: 'זמר', t: 'semer', b: 'Gesang' },
    { w: 'חלום', t: 'chalom', b: 'Traum' },
    { w: 'מלאכה', t: 'melacha', b: 'Werk, Arbeit' },
    { w: 'מנוחה', t: 'menucha', b: 'Ruhe' },
    { w: 'חרות', t: 'cherut', b: 'Freiheit' },
    { w: 'גלות', t: 'galut', b: 'Verbannung' },
    { w: 'קהל', t: 'kahal', b: 'Versammlung' },
    { w: 'עדה', t: 'eda', b: 'Gemeinde' },
    { w: 'שבט', t: 'schewet', b: 'Stamm, Stab' },
    { w: 'מטה', t: 'mate', b: 'Stab, Stamm' },
    { w: 'דם', t: 'dam', b: 'Blut' },
    { w: 'בשר', t: 'bassar', b: 'Fleisch' },
    { w: 'עצם', t: 'ezem', b: 'Knochen, Wesen' },
    { w: 'זרע', t: 'sera', b: 'Same, Nachkommen' },
    { w: 'פרי', t: 'pri', b: 'Frucht' },
    { w: 'שדה', t: 'sade', b: 'Feld' },
    { w: 'צאן', t: 'zon', b: 'Kleinvieh' },
    { w: 'רעה', t: 'roe', b: 'Hirte' },
    { w: 'כבש', t: 'kewes', b: 'Lamm' },
    { w: 'איל', t: 'ajil', b: 'Widder' },
    { w: 'יונה', t: 'jona', b: 'Taube' },
    { w: 'נשר', t: 'nescher', b: 'Adler' },
    { w: 'ארי', t: 'ari', b: 'Löwe' },
    { w: 'נחש', t: 'nachasch', b: 'Schlange' },
    { w: 'שקר', t: 'scheker', b: 'Lüge' },
    { w: 'חטא', t: 'chet', b: 'Verfehlung' },
    { w: 'מות', t: 'mawet', b: 'Tod' },
    { w: 'קבר', t: 'kewer', b: 'Grab' },
    { w: 'יתום', t: 'jatom', b: 'Waise' },
    { w: 'אלמנה', t: 'almana', b: 'Witwe' },
    { w: 'גר', t: 'ger', b: 'Fremder, Zugewanderter' },
    { w: 'עני', t: 'ani', b: 'Armer' },
    { w: 'מלחמה', t: 'milchama', b: 'Krieg' },
    { w: 'חרב', t: 'cherew', b: 'Schwert' },
    { w: 'מגן', t: 'magen', b: 'Schild' },
    { w: 'עבד', t: 'ewed', b: 'Knecht, Diener' },
    { w: 'חפש', t: 'chofesch', b: 'Freiheit' },
  ];

  return WOERTER;
});
